In [1]:
import os 
import json
import pandas as pd

In [52]:
%%time
for filename in os.listdir():
    if '.json' in filename:
        print("Processing file: ", filename)
        dutch_tweets = pd.read_json(filename)
        print(dutch_tweets.shape)
        print(dutch_tweets.columns)

Processing file:  dutch_tweets_chunk1.json
(27142, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Processing file:  dutch_tweets_chunk2.json
(27130, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Processing file:  dutch_tweets_chunk5.json
(27104, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Processing file:  dutch_tweets_chunk7.json
(27234, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Processing file:  dutch_tweets_chunk9.json
(27221, 23)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'point_info', 'point', 'latitude', 'longitude', 'altitude',
       'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Processing file:  dutch_tweets_chunk6.json
(27026, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Processing file:  dutch_tweets_chunk3.json
(27112, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Processing file:  dutch_tweets_chunk4.json
(27217, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Processing file:  dutch_tweets_chunk0.json
(27019, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Processing file:  dutch_tweets_chunk8.json
(27137, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
CPU times: user 42.1 s, sys: 772 ms, total: 42.9 s
Wall time: 42.9 s

In [56]:
%%time
for filename in os.listdir():
    if '.json' in filename:
        print("Processing file: ", filename)
        dutch_tweets = pd.read_json(filename)
        print(dutch_tweets.shape)
        print(dutch_tweets.columns)
        colnames = list(dutch_tweets.columns)
        
        #Drop the Day column
        if "Day" in colnames:
            dutch_tweets.drop(['Day'], inplace=True, axis=1)
            colnames.remove('Day')
            
        colnames = [col.lower().replace(" ", "_").replace(".nl", "") for col in colnames]
        dutch_tweets.columns = colnames
        
        dutch_tweets = dutch_tweets[['full_text', 'text_translation', 'created_at', 'screen_name', 'description', 'desc_translation',
                                     'weekofyear', 'weekday', 'day', 'month', 'year',
                                     'location', 'point_info', 'point', 'latitude', 'longitude', 'altitude', 'province', 
                                     'hisco_standard', 'hisco_code', 'industry',
                                     'sentiment_pattern', 'subjective_pattern']]
        
        #convert to json format
        result = dutch_tweets.to_json(orient="records")
        parsed = json.loads(result)

        # Create the json filename
        file_comp = list()
        file_comp.append("dutch-tweets")
        file_comp.append(filename)
        json_filename = "/".join(file_comp)
        
        print("Output file: ", json_filename)
        with open(json_filename, 'w') as outfile:
            json.dump(parsed, outfile)
        
        #Convert created_at and object cols to string 
        
        #Write the excel file
#         excel_filename = filename[:-4] + 'xlsx'
#         dutch_tweets.to_excel(excel_filename, index=False)
        
        
        print("####################################################")
        print("####################################################")

Processing file:  dutch_tweets_chunk1.json
(27142, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Output file:  dutch-tweets/dutch_tweets_chunk1.json
####################################################
####################################################
Processing file:  dutch_tweets_chunk2.json
(27130, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Output file:  dutch-tweets/dutch_tweets_chunk2.json
####################################################
####################################################
Processing file:  dutch_tweets_chunk5.json
(27104, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Output file:  dutch-tweets/dutch_tweets_chunk5.json
####################################################
####################################################
Processing file:  dutch_tweets_chunk7.json
(27234, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Output file:  dutch-tweets/dutch_tweets_chunk7.json
####################################################
####################################################
Processing file:  dutch_tweets_chunk9.json
(27221, 23)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'point_info', 'point', 'latitude', 'longitude', 'altitude',
       'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Output file:  dutch-tweets/dutch_tweets_chunk9.json
####################################################
####################################################
Processing file:  dutch_tweets_chunk6.json
(27026, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Output file:  dutch-tweets/dutch_tweets_chunk6.json
####################################################
####################################################
Processing file:  dutch_tweets_chunk3.json
(27112, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Output file:  dutch-tweets/dutch_tweets_chunk3.json
####################################################
####################################################
Processing file:  dutch_tweets_chunk4.json
(27217, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Output file:  dutch-tweets/dutch_tweets_chunk4.json
####################################################
####################################################
Processing file:  dutch_tweets_chunk0.json
(27019, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Output file:  dutch-tweets/dutch_tweets_chunk0.json
####################################################
####################################################
Processing file:  dutch_tweets_chunk8.json
(27137, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')
Output file:  dutch-tweets/dutch_tweets_chunk8.json
####################################################
####################################################
CPU times: user 1min 1s, sys: 687 ms, total: 1min 2s
Wall time: 1min 8s

In [25]:
colnames = dutch_tweets.columns

In [26]:
colnames = [col.lower().replace(" ", "_").replace(".nl", "") for col in colnames]

In [27]:
dutch_tweets.columns = colnames

In [48]:
dutch_tweets = dutch_tweets[['full_text', 'text_translation', 'created_at', 'screen_name', 'description', 'desc_translation', 'weekofyear', 'weekday', 'day', 'month', 'year', 'location', 'point_info', 'point', 'latitude', 'longitude', 'altitude', 'province', 'hisco_standard', 'hisco_code', 'industry', 'sentiment_pattern', 'subjective_pattern']]

In [53]:
dutch_tweets.drop(['Day'], inplace=True)

KeyError: "['Day'] not found in axis"

In [49]:
dutch_tweets.to_excel("temp.xlsx", index=False)

ValueError: Excel does not support datetimes with timezones. Please ensure that datetimes are timezone unaware before writing to Excel.

In [50]:
dutch_tweets.dtypes

full_text                          object
text_translation                   object
created_at            datetime64[ns, UTC]
screen_name                        object
description                        object
desc_translation                   object
weekofyear                          int64
weekday                             int64
day                                 int64
day                                 int64
month                               int64
year                                int64
location                           object
point_info                         object
point                              object
latitude                          float64
longitude                         float64
altitude                          float64
province                           object
hisco_standard                     object
hisco_code                         object
industry                             bool
sentiment_pattern                 float64
subjective_pattern                float64
dtype: object

In [32]:
colnames = list(set(colnames))

In [34]:
colnames

['point_info',
 'full_text',
 'year',
 'description',
 'point',
 'altitude',
 'weekday',
 'subjective_pattern',
 'sentiment_pattern',
 'industry',
 'location',
 'month',
 'longitude',
 'province',
 'latitude',
 'day',
 'hisco_code',
 'desc_translation',
 'screen_name',
 'weekofyear',
 'text_translation',
 'created_at',
 'hisco_standard']

In [41]:
for col in colnames:
    if isinstance(dutch_tweets[col].dtypes, object) or isinstance(dutch_tweets[col].dtypes, datetime):
        print(col)

point_info
full_text
year
description
point
altitude
weekday
subjective_pattern
sentiment_pattern
industry
location
month
longitude
province
latitude
day
hisco_code
desc_translation
screen_name
weekofyear
text_translation
created_at
hisco_standard

In [51]:
dutch_tweets.head(5)

,full_text,text_translation,created_at,screen_name,description,desc_translation,weekofyear,weekday,day,day,...,point,latitude,longitude,altitude,province,hisco_standard,hisco_code,industry,sentiment_pattern,subjective_pattern
0,"@DariusXVI @2deKamerFVD Ach kom op,Griekenland...","@DariusXVI @ 2deKamerFVD Oh come on, Greece wa...",2020-08-31 18:21:59+00:00,zzkunkzz,"Trotse koihouder,bestudeerd(e)koiziekten en KH...",Proud koihouder studied (e) koiziekten and KHV...,36,0,31,31,...,"(52.5001698, 5.7480821, 0.0)",52.50017,5.748082,0.0,Flevoland,None,None,False,0.106250,0.837500
1,"Men stond niet onder druk, men zette burgers o...","It was not under pressure, they put people und...",2020-09-01 08:44:56+00:00,RNas71,Gotta be ya own dawg - Conspiracy ≠ theory - A...,Gotta be ya own dawg - Conspiracy theory ≠ - A...,36,1,1,1,...,"(52.3727598, 4.8936041, 0.0)",52.37276,4.893604,0.0,Noord-Holland,None,None,False,-0.279167,0.608333
2,"Men stond niet onder druk, men zette burgers o...","It was not under pressure, they put people und...",2020-09-01 08:44:56+00:00,RNas71,Gotta be ya own dawg - Conspiracy ≠ theory - A...,Gotta be ya own dawg - Conspiracy theory ≠ - A...,36,1,1,1,...,"(52.3727598, 4.8936041, 0.0)",52.37276,4.893604,0.0,Noord-Holland,None,None,False,-0.279167,0.608333
3,Ik ben echt wel klaar met bedrijven en mensen ...,I'm really done with companies and people who ...,2020-08-31 18:22:00+00:00,JPvonD,Kal-el wannabe | Dierenvriend | Mug | Boogschu...,Kal-el wannabe | Animal Lover | mug | Sagittar...,36,0,31,31,...,None,NaN,NaN,NaN,None,None,None,False,0.104167,0.575000
4,#PlandemicHoax https://t.co/kz65jOBXJy,#PlandemicHoax https://t.co/kz65jOBXJy,2020-09-01 08:44:57+00:00,Zoetnet,"Heart of gold, nerves of steel, knob of butter...","Heart of gold, nerves of steel, knob of butter...",36,1,1,1,...,"(52.5001698, 5.7480821, 0.0)",52.50017,5.748082,0.0,Flevoland,None,None,False,0.000000,0.000000

In [11]:
dutch_tweets = pd.read_json(filename)
print(dutch_tweets.shape)
print(dutch_tweets.columns)
dutch_tweets.head()

(27142, 24)
Index(['full_text', 'text Translation', 'created_at', 'screen_name',
       'description', 'desc Translation', 'location', 'Weekday', 'Month',
       'Year', 'Day', 'point_info', 'point', 'latitude', 'longitude',
       'altitude', 'Province', 'hisco_standard', 'hisco_code', 'Industry',
       'Sentiment_pattern.nl', 'Subjective_pattern.nl', 'weekofyear', 'day'],
      dtype='object')

,full_text,text Translation,created_at,screen_name,description,desc Translation,location,Weekday,Month,Year,...,longitude,altitude,Province,hisco_standard,hisco_code,Industry,Sentiment_pattern.nl,Subjective_pattern.nl,weekofyear,day
0,"@DariusXVI @2deKamerFVD Ach kom op,Griekenland...","@DariusXVI @ 2deKamerFVD Oh come on, Greece wa...",2020-08-31 18:21:59+00:00,zzkunkzz,"Trotse koihouder,bestudeerd(e)koiziekten en KH...",Proud koihouder studied (e) koiziekten and KHV...,Netherlands,0,8,2020,...,5.748082,0.0,Flevoland,None,None,False,0.106250,0.837500,36,31
1,"Men stond niet onder druk, men zette burgers o...","It was not under pressure, they put people und...",2020-09-01 08:44:56+00:00,RNas71,Gotta be ya own dawg - Conspiracy ≠ theory - A...,Gotta be ya own dawg - Conspiracy theory ≠ - A...,Amsterdam,1,9,2020,...,4.893604,0.0,Noord-Holland,None,None,False,-0.279167,0.608333,36,1
2,"Men stond niet onder druk, men zette burgers o...","It was not under pressure, they put people und...",2020-09-01 08:44:56+00:00,RNas71,Gotta be ya own dawg - Conspiracy ≠ theory - A...,Gotta be ya own dawg - Conspiracy theory ≠ - A...,Amsterdam,1,9,2020,...,4.893604,0.0,Noord-Holland,None,None,False,-0.279167,0.608333,36,1
3,Ik ben echt wel klaar met bedrijven en mensen ...,I'm really done with companies and people who ...,2020-08-31 18:22:00+00:00,JPvonD,Kal-el wannabe | Dierenvriend | Mug | Boogschu...,Kal-el wannabe | Animal Lover | mug | Sagittar...,The Multiverse,0,8,2020,...,NaN,NaN,None,None,None,False,0.104167,0.575000,36,31
4,#PlandemicHoax https://t.co/kz65jOBXJy,#PlandemicHoax https://t.co/kz65jOBXJy,2020-09-01 08:44:57+00:00,Zoetnet,"Heart of gold, nerves of steel, knob of butter...","Heart of gold, nerves of steel, knob of butter...",The Netherlands,1,9,2020,...,5.748082,0.0,Flevoland,None,None,False,0.000000,0.000000,36,1

In [47]:
dutch_tweets.columns

Index(['full_text', 'text_translation', 'created_at', 'screen_name',
       'description', 'desc_translation', 'weekofyear', 'weekday', 'day',
       'day', 'month', 'year', 'location', 'point_info', 'point', 'latitude',
       'longitude', 'altitude', 'province', 'hisco_standard', 'hisco_code',
       'industry', 'sentiment_pattern', 'subjective_pattern'],
      dtype='object')