In [12]:
import os 
import pandas as pd
import numpy as np

filenames = list()
for file in os.listdir("/home/ubuntu"):
    if file.endswith("json"):
        filenames.append(file)
        
print(filenames)

['dutch_tweets_chunk1.json', 'dutch_tweets_chunk2.json', 'dutch_tweets_chunk5.json', 'dutch_tweets_chunk7.json', 'dutch_tweets_chunk9.json', 'dutch_tweets_chunk6.json', 'dutch_tweets_chunk3.json', 'dutch_tweets_chunk4.json', 'dutch_tweets_chunk0.json', 'dutch_tweets_chunk8.json']

In [14]:
dutch_tweets = pd.read_json(filenames[0])
print(dutch_tweets.shape)
dutch_tweets.head()

(27142, 23)

,full_text,text_translation,created_at,screen_name,description,desc_translation,weekofyear,weekday,day,month,...,point,latitude,longitude,altitude,province,hisco_standard,hisco_code,industry,sentiment_pattern,subjective_pattern
0,"@DariusXVI @2deKamerFVD Ach kom op,Griekenland...","@DariusXVI @ 2deKamerFVD Oh come on, Greece wa...",2020-08-31 18:21:59,zzkunkzz,"Trotse koihouder,bestudeerd(e)koiziekten en KH...",Proud koihouder studied (e) koiziekten and KHV...,36,0,31,8,...,"(52.5001698, 5.7480821, 0.0)",52.50017,5.748082,0.0,Flevoland,None,None,False,0.106250,0.837500
1,"Men stond niet onder druk, men zette burgers o...","It was not under pressure, they put people und...",2020-09-01 08:44:56,RNas71,Gotta be ya own dawg - Conspiracy ≠ theory - A...,Gotta be ya own dawg - Conspiracy theory ≠ - A...,36,1,1,9,...,"(52.3727598, 4.8936041, 0.0)",52.37276,4.893604,0.0,Noord-Holland,None,None,False,-0.279167,0.608333
2,"Men stond niet onder druk, men zette burgers o...","It was not under pressure, they put people und...",2020-09-01 08:44:56,RNas71,Gotta be ya own dawg - Conspiracy ≠ theory - A...,Gotta be ya own dawg - Conspiracy theory ≠ - A...,36,1,1,9,...,"(52.3727598, 4.8936041, 0.0)",52.37276,4.893604,0.0,Noord-Holland,None,None,False,-0.279167,0.608333
3,Ik ben echt wel klaar met bedrijven en mensen ...,I'm really done with companies and people who ...,2020-08-31 18:22:00,JPvonD,Kal-el wannabe | Dierenvriend | Mug | Boogschu...,Kal-el wannabe | Animal Lover | mug | Sagittar...,36,0,31,8,...,None,NaN,NaN,NaN,None,None,None,False,0.104167,0.575000
4,#PlandemicHoax https://t.co/kz65jOBXJy,#PlandemicHoax https://t.co/kz65jOBXJy,2020-09-01 08:44:57,Zoetnet,"Heart of gold, nerves of steel, knob of butter...","Heart of gold, nerves of steel, knob of butter...",36,1,1,9,...,"(52.5001698, 5.7480821, 0.0)",52.50017,5.748082,0.0,Flevoland,None,None,False,0.000000,0.000000

In [25]:
for file in filenames:
    print(f"Reading file...{file}")
    dutch_tweets = pd.read_json(file)
    print("Writing to excel...")
    print(f"Shape of you...{dutch_tweets.shape}")
    
    excel_file = file[:-4] + "xlsx"
    dutch_tweets.to_excel(excel_file, index=False)

Reading file...dutch_tweets_chunk1.json
Writing to excel...
Shape of you...(27142, 23)
Reading file...dutch_tweets_chunk2.json
Writing to excel...
Shape of you...(27130, 23)
Reading file...dutch_tweets_chunk5.json
Writing to excel...
Shape of you...(27104, 23)
Reading file...dutch_tweets_chunk7.json
Writing to excel...
Shape of you...(27234, 23)
Reading file...dutch_tweets_chunk9.json
Writing to excel...
Shape of you...(27221, 23)
Reading file...dutch_tweets_chunk6.json
Writing to excel...
Shape of you...(27026, 23)
Reading file...dutch_tweets_chunk3.json
Writing to excel...
Shape of you...(27112, 23)
Reading file...dutch_tweets_chunk4.json
Writing to excel...
Shape of you...(27217, 23)
Reading file...dutch_tweets_chunk0.json
Writing to excel...
Shape of you...(27019, 23)
Reading file...dutch_tweets_chunk8.json
Writing to excel...
Shape of you...(27137, 23)